server:
  port: 8080

spring:
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enjoytrips?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 91b0fd343b38cd01c199c2e89f97c729
            client-secret: FOYNh4Av4t5YVjcK5CPZ1AyOqcERN4Mg
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: fongfongtripfongfongtripfongfongtripfongfongtripfongfongtripfongfongtripfongfongtripfongfongtripfongfongtripfongfongtripfongfongtripfongfongtripfongfongtrip

client:
  host: localhost
  url: http://localhost:3000
  #  url: http://70.12.50.219:3000
  endpoint: /success